# Generated by Django 5.1.1 on 2024-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('yeargraduated', models.CharField(choices=[('Y1',"2019"), ('Y2', "2020"), ('Y3', "2021"), ('Y4',"2022"), ('Y5', "2023")],max_length=2)),
                ('college', models.CharField(choices=[('CAH', "College of Arts and Humanities"), ('CS', "College of Sciences")], max_length=3)),
                ('program', models.CharField(choices=[('BSIT', "Bachelor of Science in Information Techonology"), ('BSCS', "Bachelor of Science in Computer Sciences")], max_length=4)),
                ('district', models.CharField(choices=[('D1', "District 1"), ('D2', "District 2")],max_length=2)),
            ],
        ),
    ]
