# Generated by Django 5.1.1 on 2024-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='district',
            field=models.CharField(choices=[('D1', 'DISTRICT 1'), ('D2', 'DISTRICT 2')], max_length=2),
        ),
    ]
