# Generated by Django 5.1.1 on 2024-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_alumni_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='yeargraduated',
            field=models.IntegerField(choices=[('Y1', '2019'), ('Y2', '2020'), ('Y3', '2021'), ('Y4', '2022'), ('Y5', '2023')], max_length=2),
        ),
    ]
