# Generated by Django 5.1.1 on 2024-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_alumni_yeargraduated_alumni_yeargraduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='yearGraduated',
            field=models.IntegerField(default=0),
        ),
    ]
