# Generated by Django 5.1.1 on 2024-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_alumni_yeargraduated_alumni_year_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='year_graduated',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=0),
        ),
    ]
